# Generated by Django 6.0.4 on 2026-05-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(choices=[('kerala', 'Kerala'), ('delhi', 'Delhi'), ('bengaluru', 'Bengaluru'), ('mumbai', 'Mumbai'), ('chennai', 'Chennai'), ('kolkata', 'Kolkata'), ('jaipur', 'Jaipur'), ('ahmedabad', 'Ahmedabad'), ('pune', 'Pune')], max_length=50)),
                ('style', models.CharField(choices=[('portrait', 'Portrait'), ('abstract', 'Abstract'), ('watercolour', 'Watercolour'), ('oil', 'Oil Painting'), ('sketch', 'Sketch'), ('digital', 'Digital'), ('mandala', 'Mandala'), ('mural', 'Mural')], max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('rating', models.FloatField(default=0.0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
