# Generated by Django 6.0.4 on 2026-05-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
    ]
