# Generated by Django 6.0.4 on 2026-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artistprofile_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='mediums',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
