# Generated by Django 6.0.4 on 2026-05-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('artwork_size', models.CharField(blank=True, max_length=50)),
                ('delivery', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('both', 'Both')], default='digital', max_length=20)),
                ('preferred_date', models.DateField()),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='references/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='artists.artistprofile')),
            ],
        ),
    ]
